<?php

return [
  'twitter' => [
    'API_KEY_TWITTER' => env('API_KEY_TWITTER'),
    'API_KEY_SECRET_TWITTER' => env('API_KEY_SECRET_TWITTER'),
    'BEARER_TOKEN_TWITTER' => env('BEARER_TOKEN_TWITTER'),
    'ACCESS_TOKEN_TWITTER' => env('ACCESS_TOKEN_TWITTER'),
    'ACCESS_TOKEN_SECRET_TWITTER' => env('ACCESS_TOKEN_SECRET_TWITTER'),
  ]
];
